"use strict";
//I have a temp array until I learn how to parse the array
Object.defineProperty(exports, "__esModule", { value: true });
exports.tempWords = void 0;
exports.tempWords = [
    "vacuum",
    "continuum",
    "luxury",
    "xylophone",
    "quartz",
    "quiz",
    "catapult",
    "cater",
    "strengths",
    "rhythms",
    "symphony",
    "unquestionably",
    "box",
    "buxom",
    "yesterday",
    "yummy",
    "crypt",
    "gypsy",
    "aeiou",
    "facetious",
    "sequoia",
    "educationally",
    "queue",
    "muumuu",
    "buxomly",
    "exquisite",
    "taxonomy",
    "quixotic",
    "yakuza",
    "catty",
    "catalog",
    "crystal",
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "subsequent",
    "ambiguous",
    "juxtapose",
    "zealous",
    "xylography",
    "UU",
    "uu",
    "UUYUUYUUUU",
];
