// How many words contain the substring "TYPE”?
// import { tempWords } from "../scripts/tempWordList";
var words2 = [
    "vacuum",
    "continuum",
    "luxury",
    "xylophone",
    "quartz",
    "quiz",
    "catapult",
    "cater",
    "strengths",
    "rhythms",
    "symphony",
    "unquestionably",
    "box",
    "buxom",
    "yesterday",
    "yummy",
    "crypt",
    "gypsy",
    "aeiou",
    "facetious",
    "sequoia",
    "educationally",
    "queue",
    "muumuu",
    "buxomly",
    "exquisite",
    "taxonomy",
    "quixotic",
    "yakuza",
    "catty",
    "catalog",
    "crystal",
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "subsequent",
    "ambiguous",
    "juxtapose",
    "zealous",
    "xylography",
    "UU",
    "uu",
    "UUYUUYUUUU",
    "qat",
    "scats",
    "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
    "hohohohohohohohohohohohohohohoohohohohohohohhohohoho",
    "sh",
    "mm",
    "MM",
    "typescript",
    "architype",
    "subtype",
];
// How many words contain the substring "TYPE”?
function howManyWordsContainStrType(arr) {
    return arr.filter(function (word) { return word.includes("type"); }).length;
}
console.log(howManyWordsContainStrType(words2));
