const words3: string[] = [
  "vacuum",
  "continuum",
  "luxury",
  "xylophone",
  "quartz",
  "quiz",
  "catapult",
  "cater",
  "strengths",
  "rhythms",
  "symphony",
  "unquestionably",
  "box",
  "buxom",
  "yesterday",
  "yummy",
  "crypt",
  "gypsy",
  "aeiou",
  "facetious",
  "sequoia",
  "educationally",
  "queue",
  "muumuu",
  "buxomly",
  "exquisite",
  "taxonomy",
  "quixotic",
  "yakuza",
  "catty",
  "catalog",
  "crystal",
  "pneumonoultramicroscopicsilicovolcanoconiosis",
  "subsequent",
  "ambiguous",
  "juxtapose",
  "zealous",
  "xylography",
  "UU",
  "uu",
  "UUYUUYUUUU",
  "qat",
  "scats",
  "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
  "hohohohohohohohohohohohohohohoohohohohohohohhohohoho",
  "sh",
  "mm",
  "MM",
  "typescript",
  "architype",
  "subtype",
  "nightly",
  "unsightly",
  "ghtlyere9",
  "unsightlyy",
];

// Create and print an array containing all of the words that end in "GHTLY"

function printArrayContainingAllWordsEndingInGhtly(arr: string[]) {
  console.log(arr.filter((word) => word.slice(-5) === "ghtly"));
}

printArrayContainingAllWordsEndingInGhtly(words3);
